---
abstract: 'map VMethod for Template::Tookit'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Template::Test: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Template-Plugin-Map
requires:
  Template: '2.0'
  Template::Plugin::VMethods: '0'
  base: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Plugin-Map
  homepage: http://search.cpan.org/dist/Template-Plugin-Map/
  repository: git://github.com/mschout/template-plugin-map.git
version: '0.03'
x_serialization_backend: 'YAML::Tiny version 1.69'
